//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIAS
    {
        public CATEGORIAS()
        {
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
            this.SUMINISTROS = new HashSet<SUMINISTROS>();
            this.RECETAS = new HashSet<RECETAS>();
        }
    
        public int id_categoria { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual ICollection<SUMINISTROS> SUMINISTROS { get; set; }
        public virtual ICollection<RECETAS> RECETAS { get; set; }
    }
}
