//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        public CATEGORIA()
        {
            this.PRODUCTOS = new HashSet<PRODUCTO>();
            this.RECETAS = new HashSet<RECETA>();
            this.SUMINISTROS = new HashSet<SUMINISTRO>();
        }
    
        public int id_categoria { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTOS { get; set; }
        public virtual ICollection<RECETA> RECETAS { get; set; }
        public virtual ICollection<SUMINISTRO> SUMINISTROS { get; set; }
    }
}
