//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public DbSet<CONTACTOS> CONTACTOS { get; set; }
        public DbSet<DETALLE_ORDENES> DETALLE_ORDENES { get; set; }
        public DbSet<DETALLE_RECETAS> DETALLE_RECETAS { get; set; }
        public DbSet<EVENTOS> EVENTOS { get; set; }
        public DbSet<IMAGENES_PRODUCTOS> IMAGENES_PRODUCTOS { get; set; }
        public DbSet<INGREDIENTES> INGREDIENTES { get; set; }
        public DbSet<ORDENES> ORDENES { get; set; }
        public DbSet<ORDENES_ESTADOS> ORDENES_ESTADOS { get; set; }
        public DbSet<ORDENES_PAGO_ESTADOS> ORDENES_PAGO_ESTADOS { get; set; }
        public DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public DbSet<RECETAS> RECETAS { get; set; }
        public DbSet<SUMINISTROS> SUMINISTROS { get; set; }
        public DbSet<TIPOS_EVENTOS> TIPOS_EVENTOS { get; set; }
        public DbSet<UNIDADES_MEDIDA> UNIDADES_MEDIDA { get; set; }
        public DbSet<DETALLE_PRODUCTOS> DETALLE_PRODUCTOS { get; set; }
    }
}
