//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTOS
    {
        public CONTACTOS()
        {
            this.EVENTOS = new HashSet<EVENTOS>();
            this.ORDENES = new HashSet<ORDENES>();
        }
    
        public int id_contacto { get; set; }
        public string nombre_apellido { get; set; }
        public string tipo { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string fuente { get; set; }
        public string direccion { get; set; }
        public string producto_que_provee { get; set; }
        public bool desea_recibir_correos { get; set; }
        public bool desea_recibir_whatsapp { get; set; }
        public string informacion_personal { get; set; }
    
        public virtual ICollection<EVENTOS> EVENTOS { get; set; }
        public virtual ICollection<ORDENES> ORDENES { get; set; }
    }
}
