//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PRODUCTO
    {
        public int id_producto { get; set; }
        public Nullable<int> id_suministro { get; set; }
        public Nullable<int> id_receta { get; set; }
        public int cantidad { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual RECETA RECETA { get; set; }
        public virtual SUMINISTRO SUMINISTRO { get; set; }
    }
}
