//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDENES
    {
        public int id_orden { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public int producto_porciones { get; set; }
        public decimal producto_costo { get; set; }
        public decimal producto_precio { get; set; }
    
        public virtual ORDENES ORDENES { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
