//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public DbSet<CONTACTO> CONTACTOS { get; set; }
        public DbSet<DETALLE_ORDEN> DETALLE_ORDENES { get; set; }
        public DbSet<DETALLE_RECETA> DETALLE_RECETAS { get; set; }
        public DbSet<EVENTO> EVENTOS { get; set; }
        public DbSet<IMAGEN_PRODUCTO> IMAGENES_PRODUCTOS { get; set; }
        public DbSet<INGREDIENTE> INGREDIENTES { get; set; }
        public DbSet<ORDEN> ORDENES { get; set; }
        public DbSet<ORDEN_ESTADO> ORDENES_ESTADOS { get; set; }
        public DbSet<ORDEN_PAGO_ESTADO> ORDENES_PAGO_ESTADOS { get; set; }
        public DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public DbSet<RECETA> RECETAS { get; set; }
        public DbSet<SUMINISTRO> SUMINISTROS { get; set; }
        public DbSet<TIPO_EVENTO> TIPOS_EVENTOS { get; set; }
        public DbSet<UNIDAD_MEDIDA> UNIDADES_MEDIDA { get; set; }
        public DbSet<DETALLE_PRODUCTO> DETALLE_PRODUCTOS { get; set; }
    }
}
