//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOS
    {
        public int id_evento { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_cliente { get; set; }
        public int id_orden { get; set; }
        public int id_tipo_evento { get; set; }
    
        public virtual CONTACTOS CONTACTOS { get; set; }
        public virtual ORDENES ORDENES { get; set; }
        public virtual TIPOS_EVENTOS TIPOS_EVENTOS { get; set; }
    }
}
