//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGENES_PRODUCTOS
    {
        public int id_imagen { get; set; }
        public int id_producto { get; set; }
        public string url { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
