//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENTE
    {
        public INGREDIENTE()
        {
            this.DETALLE_RECETAS = new HashSet<DETALLE_RECETA>();
        }
    
        public int id_ingrediente { get; set; }
        public string nombre { get; set; }
        public double cantidad { get; set; }
        public int id_unidad { get; set; }
        public decimal costo { get; set; }
        public string proveedor { get; set; }
    
        public virtual ICollection<DETALLE_RECETA> DETALLE_RECETAS { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
    }
}
