//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_ESTADO
    {
        public ORDEN_ESTADO()
        {
            this.ORDENES = new HashSet<ORDEN>();
        }
    
        public int id_orden_estado { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<ORDEN> ORDENES { get; set; }
    }
}
