//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_PAGO_ESTADOS
    {
        public ORDENES_PAGO_ESTADOS()
        {
            this.ORDENES = new HashSet<ORDENES>();
        }
    
        public int id_orden_pago_estado { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<ORDENES> ORDENES { get; set; }
    }
}
