//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public ORDEN()
        {
            this.DETALLE_ORDENES = new HashSet<DETALLE_ORDEN>();
        }
    
        public int id_orden { get; set; }
        public int id_cliente { get; set; }
        public string tipo_entrega { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> descuento_porcentaje { get; set; }
        public Nullable<decimal> costo_envio { get; set; }
        public string direccion_entrega { get; set; }
        public System.TimeSpan hora_entrega { get; set; }
        public Nullable<int> id_orden_estado { get; set; }
        public Nullable<int> id_orden_pago_estado { get; set; }
        public Nullable<int> id_evento { get; set; }
    
        public virtual CONTACTO CLIENTE { get; set; }
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDENES { get; set; }
        public virtual EVENTO EVENTO { get; set; }
        public virtual ORDEN_ESTADO ESTADO { get; set; }
        public virtual ORDEN_PAGO_ESTADO ESTADO_PAGO { get; set; }
    }
}
