//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public PRODUCTOS()
        {
            this.DETALLE_ORDENES = new HashSet<DETALLE_ORDENES>();
            this.IMAGENES_PRODUCTOS = new HashSet<IMAGENES_PRODUCTOS>();
            this.DETALLE_PRODUCTOS = new HashSet<DETALLE_PRODUCTOS>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int porciones { get; set; }
        public decimal horas_trabajo { get; set; }
        public string tipo_precio { get; set; }
        public decimal valor_precio { get; set; }
        public int id_categoria { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        public virtual ICollection<DETALLE_ORDENES> DETALLE_ORDENES { get; set; }
        public virtual ICollection<IMAGENES_PRODUCTOS> IMAGENES_PRODUCTOS { get; set; }
        public virtual ICollection<DETALLE_PRODUCTOS> DETALLE_PRODUCTOS { get; set; }
    }
}
