//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.DETALLE_RECETAS = new HashSet<DETALLE_RECETA>();
            this.DETALLE_PRODUCTOS = new HashSet<DETALLE_PRODUCTO>();
        }
    
        public int id_receta { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
        public Nullable<decimal> precio_personalizado { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<DETALLE_RECETA> DETALLE_RECETAS { get; set; }
        public virtual ICollection<DETALLE_PRODUCTO> DETALLE_PRODUCTOS { get; set; }
    }
}
