//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUMINISTROS
    {
        public SUMINISTROS()
        {
            this.DETALLE_PRODUCTOS = new HashSet<DETALLE_PRODUCTOS>();
        }
    
        public int id_suministro { get; set; }
        public int id_categoria { get; set; }
        public string nombre { get; set; }
        public string proveedor { get; set; }
        public double cantidad { get; set; }
        public decimal costo { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        public virtual ICollection<DETALLE_PRODUCTOS> DETALLE_PRODUCTOS { get; set; }
    }
}
