//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_EVENTO
    {
        public TIPO_EVENTO()
        {
            this.EVENTOS = new HashSet<EVENTO>();
        }
    
        public int id_tipo_evento { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<EVENTO> EVENTOS { get; set; }
    }
}
